name: Meta Ads Reminder

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'   # jam 07:00 WIB

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install requests
        run: pip install requests

      - name: Run script
        env:
          META_TOKEN: ${{ secrets.META_TOKEN }}
          AD_ACCOUNT_ID: ${{ secrets.AD_ACCOUNT_ID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python check_balance.py
